import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/layout/navbar";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  // Specify weight yang dibutuhkan
  weight: ["300", "400", "500", "600", "700", "800"],
  // Optionally, specify italic styles if needed
  // style: ['normal', 'italic'],
  // Optionally, specify display
  display: "swap",
  // Optionally, specify fallback
  fallback: ["system-ui", "arial"],
  // Optionally, specify variable support
  variable: "--font-plus-jakarta",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${plusJakartaSans.variable} antialiased`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
